language: node_js
node_js:
  - '10'
os:
  - linux
# Travis-CI Caching
cache:
  directories:
    - node_modules
# 只检测 master 分支的 push
branches:
  only:
    - master

install:
  - yarn install
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_token: '$NPM_TOKEN'
